{% set version = "1.1.1" %}

package:
  name: msort
  version: {{ version }}

source:
  git_url: https://github.com/alienzj/msort.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - msort -h

about:
  home: https://github.com/alienzj/msort
  license: MIT
  summary: msort, sort file rows by multiple field, written by Ruan Jue<ruanjue@genomics.org.cn>
