package:
  name: fastp
  version: "0.19.6"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - fastp --help

about:
  home: https://github.com/ohmeta/fastp
  license: MIT
  summary: A FASTQ preprocessor with full features (QC/adapters/trimming/filtering/splitting...)
