{% set version = "1.1" %}
{% set name = "VirFinder" %}
{% set sha256 = "1e1a84c541dfd6adabb47abf297dc510b60a7794dc430e8362bb501ab78595b4" %}

package:
  name: r-{{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/jessieren/{{ name }}.git

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  arch: linux-64

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - r-base
    - r-rcpp
  host:
    - r-base
    - bioconductor-qvalue
    - r-glmnet
    - r-rcpp
  run:
    - r-base
    - bioconductor-qvalue
    - r-glmnet
    - r-rcpp

  test:
    commands:
      - $R -e "library(''{{ name }}'')"

  about:
    home: https://github.com/jessieren/{{ name }}
    license: USC-RL v1.0
    summary: 'VirFinder: a novel k-mer based tool for identifying viral sequences from assembled metagenomic data'

  extra:
    copy_test_source_files: true
    final: true
